### ISSUE TITLE
how to sort the results?

### ISSUE THREAD

**Issue by sunminghong** [nedscode/memdb#3]
mdb := memdb.NewStore().
    CreateIndex("id").
    CreateIndex("project")
  mdb.CreateIndex("id").Unique()
... 

ds := mdb.In("project").Lookup(p)
    for d := range ds {
      log.Info(ds[d])
    }
...
I hope to export the result sort by "id" field,  how to do ?

**Comment by norganna** [comment]
Hi, you can use the default sort package to sort your items dependant upon your criteria.

If you have some sample data and an idea how you would like it sorted, I can assist with an example.

**Comment by norganna** [comment]
To get you started, here's a quick example. Please close the issue if this solves your request.

```go
package main

import (
	"log"
	"sort"

	"github.com/nedscode/memdb"
)

// Item is an example item.
type Item struct {
	ID      string
	Project string
}

func main() {
	mdb := memdb.NewStore()
	mdb.CreateIndex("id").Unique()
	mdb.CreateIndex("project")

	mdb.Put(&Item{
		ID:      "a1",
		Project: "Project A",
	})
	mdb.Put(&Item{
		ID:      "b4",
		Project: "Project B",
	})
	mdb.Put(&Item{
		ID:      "b2",
		Project: "Project B",
	})
	mdb.Put(&Item{
		ID:      "b1",
		Project: "Project B",
	})
	mdb.Put(&Item{
		ID:      "b3",
		Project: "Project B",
	})
	mdb.Put(&Item{
		ID:      "c1",
		Project: "Project C",
	})

	ds := mdb.In("project").Lookup("Project B")
	for _, item := range ds {
		log.Print(item)
	}

	sort.SliceStable(ds, func(i, j int) bool {
		if iItem, ok := ds[i].(*Item); ok {
			if jItem, ok := ds[j].(*Item); ok {
				return iItem.ID < jItem.ID
			}
			return true
		}
		return false
	})

	for _, item := range ds {
		log.Print(item)
	}
}
```

**Comment by norganna** [comment]
Pretty sure this has fixed the issue. Please reopen if you're still having problems.
